sudo: required
language: C
os:
  - linux
  - osx

branches:
  only:
    - master
    - dev

install:
  - sudo ./install
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew install go
        brew install dmd
        brew install rust
    fi

script:
  - xmake create -P ./test 
  - xmake -P ./test
  - ./tests/tests
