os: Visual Studio 2015

platform:
  - Win32
  - Win64

before_build:
  - cmd: curl -fsSL https://github.com/tboox/xmake/releases/download/v2.0.5/xmake-v2.0.5.exe -o xmake-installer.exe
  - cmd: mkdir program
  - cmd: xmake-installer.exe /S /D=program
  - cmd: xmake --version
  - cmd: cp -r xmake/* program/
  - cmd: xmake --version
  - cmd: ls program

build_script:
  - cmd: cd ./tests/console_c
  - cmd: if %platform%==Win32 xmake f -m debug
  - cmd: if %platform%==Win64 xmake f -m debug -a x64
  - cmd: xmake 

test_script:
  - cmd: xmake --version
