os: Visual Studio 2015

platform:
  - Win32
  - Win64

before_build:
  - cmd: call install.bat noinput

build_script:
  - cmd: cd ./tests/console_c
  - cmd: if %platform%==Win32 xmake f -m debug
  - cmd: if %platform%==Win64 xmake f -m debug -a x64
  - cmd: xmake 

test_script:
  - cmd: xmake --version
